live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[window]
dimensions = { columns = 133, lines = 40 }
decorations = "buttonless"
dynamic_title = true
dynamic_padding = false
padding = { x = 10, y = 10 }
opacity = 0.95

[selection]
save_to_clipboard = true
semantic_escape_chars = ",¿`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" }
  # { key = "Right", mods = "Alt", chars = "\u001BF" },
  # { key = "Left", mods = "Alt", chars = "\u001BB" },
  # { key = "D", mods = "Command", chars = "\u0002%" },
  # { key = "D", mods = "Command|Shift", chars = "\u0002\"" },
  # { key = "W", mods = "Command", action = "Quit" },
  # { key = "Down", mods = "Command", chars = "\u0002\u001b[B" },
  # { key = "Up", mods = "Command", chars = "\u0002\u001b[A" },
  # { key = "Left", mods = "Command", chars = "\u0002\u001b[D" },
  # { key = "Right", mods = "Command", chars = "\u0002\u001b[C" },
  # { key = "Enter", mods = "Command|Shift", chars = "\u0002z" },
]
